### ISSUE TITLE
Citation and Licensing

### ISSUE THREAD

**Issue by augustfly** [astroChasqui/q2#2]
hi @astroChasqui: I am a data editor with the AAS Journals (ApJ/AJ). Your code is being mentioned frequently in recent manuscripts submitted and accepted to our Journals. We would like to encourage you to add a "Preferred Citation" to the landing page (README.md) of this GitHub repo so that users can ensure they include the correct citation in their manuscripts. I think that [Ramirez et al. 2014, A&A, 572, A48](https://doi.org/10.1051/0004-6361/201424244) is probably the correct preferred software paper citation as it contains a description of the code. 

Notwithstanding the utter lack of any license provided by MOOG itself, I would still encourage you to add a license for your code, q2. I tend to direct folks with questions about this to Jake VanderPlas's article, "[The Whys and Hows of Licensing Scientific Code](http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/)" for questions. 

You may also want to submit this code, its description, and preferred citation to the [ASCL](http://ascl.net/submissions). You can read more about our recommendations for code developers as part of our [Journal's software policy](http://journals.aas.org/policy/software.html), which is of course more relevant to your users than yourself in this instance.

**Comment by astroChasqui** [comment]
Preferred citation and license added. Thanks!
