### ISSUE TITLE
cannot import name moog

### ISSUE THREAD

**Issue by jkteske** [astroChasqui/q2#3]
Hi, trying to run newest version of q2 and getting this error, please help!

Thanks,

Johanna

In [18]: import q2
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-18-fceb0dca6928> in <module>()
----> 1 import q2

/Users/jteske/Documents/postdoc/Jonathan/q2/__init__.py in <module>()
     13 from .config import *
     14 from .star import *
---> 15 from . import moog, specpars, errors, abundances
     16 from . import isopars
     17 import logging

/Users/jteske/Documents/postdoc/Jonathan/q2/abundances.py in <module>()
----> 1 from . import moog
      2 from .star import Star
      3 import numpy as np
      4 import datetime
      5 import logging

ImportError: cannot import name moog

**Comment by alexji** [comment]
I think this might be a python 2 vs 3 or similar thing. To import with recent versions of Anaconda+python 2, I had to replace a bunch of "from . import xxx" with "import xxx".

**Comment by alexji** [comment]
Here's the fix I did:
https://github.com/alexji/q2/tree/import-fix

If @astroChasqui wants I can submit a pull request.

**Comment by astroChasqui** [comment]
As of now q2 is only being tested with Python 3.
